# Generated by Django 5.1.1 on 2024-09-22 13:38

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("owner_photo", models.ImageField(upload_to="core/img")),
                (
                    "main_text",
                    django_ckeditor_5.fields.CKEditor5Field(verbose_name="Text"),
                ),
                ("comment_1", models.TextField(blank=True, null=True)),
                ("comment_2", models.TextField(blank=True, null=True)),
                ("comment_3", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Firma Sayfası",
                "verbose_name_plural": "Firma Sayfası",
            },
        ),
        migrations.CreateModel(
            name="BottleCapType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Ağız Şekli",
                "verbose_name_plural": "Ağız Şekilleri",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BottleColor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="Şeffaf", max_length=100, unique=True),
                ),
            ],
            options={
                "verbose_name": "Renk",
                "verbose_name_plural": "Şişe Renkleri",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BottleType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Materyal",
                "verbose_name_plural": "Şişe Materyalleri",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BottleVolume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("volume", models.PositiveIntegerField(unique=True)),
            ],
            options={
                "verbose_name": "Hacim",
                "verbose_name_plural": "Şişe Hacimleri",
                "ordering": ["volume"],
            },
        ),
        migrations.CreateModel(
            name="GeneralCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("show_navbar", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Ana Kategori",
                "verbose_name_plural": "Ana Kategoriler",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                (
                    "short_description",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "long_description",
                    django_ckeditor_5.fields.CKEditor5Field(
                        verbose_name="Uzun Açıklama"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "notes",
                    django_ckeditor_5.fields.CKEditor5Field(
                        default="", verbose_name="Notlar"
                    ),
                ),
                ("product_code", models.CharField(max_length=30)),
                (
                    "height",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Yükseklik",
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Genişlik",
                    ),
                ),
                (
                    "diameter",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Çap",
                    ),
                ),
                (
                    "depth",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="En",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Ağırlık",
                    ),
                ),
                (
                    "best_seller",
                    models.BooleanField(default=False, verbose_name="Çok Satanlar"),
                ),
                (
                    "newest",
                    models.BooleanField(default=False, verbose_name="En Yeniler"),
                ),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
                (
                    "bottle_cap_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.bottlecaptype",
                    ),
                ),
                (
                    "bottle_color",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.bottlecolor",
                    ),
                ),
                (
                    "bottle_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.bottletype",
                    ),
                ),
                (
                    "bottle_volume",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.bottlevolume",
                    ),
                ),
                ("general_category", models.ManyToManyField(to="core.generalcategory")),
            ],
            options={
                "verbose_name": "Ürün",
                "verbose_name_plural": "Ürünler",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_type",
                    models.CharField(
                        choices=[("url", "Görsel Linki"), ("upload", "Yükle")],
                        default="upload",
                        max_length=10,
                        verbose_name="Görsel Tipi",
                    ),
                ),
                (
                    "image_upload",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="core/img/",
                        verbose_name="Görsel Yükle",
                    ),
                ),
                (
                    "image_url",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Görsel Adresi"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="core.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ürün Fotoğrafı",
                "verbose_name_plural": "Ürün Fotoğrafları",
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("comment", models.TextField()),
                ("show_name", models.BooleanField(default=False)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review",
                        to="core.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Yorum",
                "verbose_name_plural": "Yorumlar",
            },
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "parent_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="core.generalcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alt Kategori",
                "verbose_name_plural": "Alt Kategoriler",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="sub_category",
            field=models.ManyToManyField(blank=True, to="core.subcategory"),
        ),
    ]
